services:
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:6333/healthz"]
      interval: 5s
      timeout: 3s
      retries: 20

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=1h
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:11434/api/tags"]
      interval: 5s
      timeout: 3s
      retries: 20
    # Uncomment for GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities: ["gpu"]

  # Optional: local dev containers for your apps (you can run them from host too)
  # mcp-server:
  #   build: ../apps/mcp-server
  #   environment:
  #     - QDRANT_URL=http://qdrant:6333
  #     - OLLAMA_URL=http://ollama:11434
  #     - EMBED_MODEL=${EMBED_MODEL:-nomic-embed-text}
  #   depends_on: [qdrant, ollama]
  #   ports: ["8711:8711"]

volumes:
  qdrant_data:
  ollama_data:
